name: 'Generate SDK from Open API Specification - Javascript'
description: 'Parses the provided Open API Specification and generates a Javascript SDK'
inputs:
  openapi-path:
    description: 'Path to the Open API Specification'
    required: true
  service-name:
    description: 'Unique name of the service the SDK supports'
    required: true
runs:
  using: "composite"
  steps:      
    - name: Copy Configuration to Workspace
      shell: bash
      run: |
        cd ${{ github.action_path }}
        mkdir ${{ github.workspace }}/../generator-config
        cp * ${{ github.workspace }}/../generator-config

    - name: Generate SDK
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: javascript
        openapi-file: ${{ inputs.openapi-path }}
        config-file: ../generator-config/config.yaml
        command-args: --invoker-package ${{ inputs.service-name }}

    - name: Check Output
      shell: bash
      run: |
        ls
        cd javascript-client
        ls
branding:
  icon: activity
  color: green
