name: 'Generate SDK from Open API Specification - Javascript'
description: 'Parses the provided Open API Specification and generates a Javascript SDK'
inputs:
  openapi-path:
    description: 'Path to the Open API Specification'
    required: true
  service-name:
    description: 'Unique name of the service the SDK supports'
    required: true
runs:
  using: "composite"
  steps:      
    - name: Copy Configuration to Workspace
      shell: bash
      run: |
        cd ${{ github.action_path }}
        mkdir -p ${{ github.workspace }}/oas-generator-config
        cp -r * ${{ github.workspace }}/oas-generator-config

    - name: Generate SDK
      uses: openapi-generators/openapitools-generator-action@v1.3.0
      with:
        generator: javascript
        openapi-file: ${{ inputs.openapi-path }}
        config-file: oas-generator-config/config.yaml
        template-dir: oas-generator-config/custom_templates
        command-args: --invoker-package ${{ inputs.service-name }} -o /github/workspace/sdk/js

    - name: Check Output
      shell: bash
      run: |
        echo "----- Root -----"
        ls
        cd sdk
        echo "----- SDK Directory -----"
        ls
        cd js
        echo "----- JS Directory -----"
        ls
        echo "-----"
branding:
  icon: activity
  color: green
