name: 'Generate SDK from Open API Specification - Javascript'
description: 'Parses the provided Open API Specification and generates a Javascript SDK'
inputs:
  openapi-path:
    description: 'Path to the Open API Specification'
    required: true
  service-name:
    description: 'Unique name of the service the SDK supports'
    required: true
runs:
  using: "composite"
  steps:      
    - name: Copy Configuration to Workspace
      shell: bash
      run: |
        echo "-----"
        echo $GITHUB_WORKSPACE
        echo ${{ github.workspace }}
        cd ${{ github.action_path }}
        mkdir ${{ github.workspace }}/oas-generator-config
        cp -r * ${{ github.workspace }}/oas-generator-config
        echo "-----"
        cd ${{ github.workspace }}
        ls
        echo "-----"
        cd oas-generator-config
        ls
        echo "-----"
        cd custom_templates
        ls
        echo "-----"

    - name: Generate SDK
      uses: openapi-generators/openapitools-generator-action@v1.3.0
      with:
        generator: javascript
        openapi-file: ${{ inputs.openapi-path }}
        config-file: oas-generator-config/config.yaml
        template-dir: oas-generator-config/custom-templates
        command-args: --invoker-package ${{ inputs.service-name }}

    - name: Check Output
      shell: bash
      run: |
        ls
        cd javascript-client
        ls
branding:
  icon: activity
  color: green
